---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: {{ component_name }}
  description: {{ description }}
  annotations:
    github.com/project-slug: {{ component_name }}
  tags:
    - api
    - openapi
spec:
  type: openapi
  lifecycle: production
  owner: {{ owner }}
  system: {{ system }}
  definition:
    $text: ./openapi.yaml
