---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: {{ component_name }}
  description: {{ description }}
  annotations:
    github.com/project-slug: {{ component_name }}
  tags:
    - http
    - express
    - nodejs
  links:
    - url: https://github.com/backstage/backstage
      title: Backstage
spec:
  type: service
  lifecycle: production
  owner: {{ owner }}
  system: {{ system }}
