app:
  baseUrl: http://localhost:3000

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  database:
    client: better-sqlite3
    connection: ':memory:'

auth:
  providers:
    guest:
      dangerouslyAllowOutsideDevelopment: true

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: main

techdocs:
  builder: local
  generator:
    runIn: local
  publisher:
    type: local
